### ISSUE TITLE
There is no 3.3v voltage regulator for GPS on PCB

### ISSUE THREAD

**Issue by usaguerrilla** [usaguerrilla/hab#15]
I had issues with running both GPS from Tiva-C I think it has 100mA limit on 3.3v current. Need to test before we change it.

**Comment by stcarlso** [comment]
The limit is supposedly 400 mA according to the Tiva C LaunchPad User Manual, which is much higher than we need. I would carefully feel the voltage regulator (U8) to ensure that it is not heating up too much.

**Comment by stcarlso** [comment]
Issue has been resolved
