### ISSUE TITLE
check if we can slow down GPS reporting their positions and trim down messages they send us.

### ISSUE THREAD

**Issue by usaguerrilla** [usaguerrilla/hab#23]
This can save a bit of power.

**Comment by stcarlso** [comment]
This can be done for the Venus with a configuration utility on a PC. Incidentally, this should dramatically reduce its own power consumption as well.

The Copernicus should be configurable over serial at runtime.

**Comment by usaguerrilla** [comment]
after talking to everybody we should shorten message delay to 10-15 seconds on last 1km of descend.

**Comment by usaguerrilla** [comment]
please note that base elevation in eastern Washington is quite higher than sea level

**Comment by usaguerrilla** [comment]
Done! It has non-volatile memory and I configured it to send only 2 messages we care about.
