### ISSUE TITLE
nmea message parsing should check message checksum

### ISSUE THREAD

**Issue by usaguerrilla** [usaguerrilla/hab#24]
reject if message is broken or mark it as unreliable?
do we really need this?

**Comment by Scorillo47** [comment]
I think so. We need some indication if packets are corrupted. 

Thanks, Adi

Date: Sun, 20 Sep 2015 22:39:43 -0700

**Comment by usaguerrilla** [comment]
didn't see any errors and it slows down processing. not big deal if one digit is wrong.
