### ISSUE TITLE
gpvtg message parsing should record if altitude is empty or 0.

### ISSUE THREAD

**Issue by usaguerrilla** [usaguerrilla/hab#36]
currently if amplitude wasn't provided by GPS field is empty and parsed value is 0.
we have a logic which changes frequency of APRS messages based on altitude. It should take into account if altitude was actually present and parsed successfully and ignore empty altitude.

(parsing code returns flag if empty value was detected, so we can keep it for future use).

**Comment by stcarlso** [comment]
This mitigation is already present, the message rate is only increased if the altitude is positive. See main.c:192.
