### ISSUE TITLE
Make sure Venus GPS has watchdog enabled

### ISSUE THREAD

**Issue by usaguerrilla** [usaguerrilla/hab#38]

**Comment by stcarlso** [comment]
This issue is unclear. What needs to be done?

**Comment by usaguerrilla** [comment]
There should be a watchdog timer in venus which should detect hangs, etc. As we are going to experience ionizing radiation it's a good idea to have it enabled and make sure it runs in case random bit flips lead to some problems/hangs.

**Comment by stcarlso** [comment]
There is no way to set this timer with an external command. If you want to attempt a GPS reset if no data is received within a certain period, we need to power cycle the whole unit, as the SparkFun board does not break out the Venus RSTN pin.
