### ISSUE TITLE
Need to send APRS messages more frequently on decend closer to the ground

### ISSUE THREAD

**Issue by usaguerrilla** [usaguerrilla/hab#5]
subj

**Comment by stcarlso** [comment]
Is this important? We want to avoid flooding the APRS system and every 30 seconds is already fairly often. Dithering was added in 75a7707 which should help.

**Comment by usaguerrilla** [comment]
Might need to chat to Lee about this. I am not sure what's the protocol here.

**Comment by stcarlso** [comment]
This is probably not necessary. Especially with the high signal quality of the PCB and the directional antenna build, increasing the signal frequency will probably just drain the battery faster on the ground.

**Comment by Scorillo47** [comment]
I think we need this. The last seconds are the most important in transmitting the exact location. 30 second interval is too large.

**Comment by usaguerrilla** [comment]
after talking to everybody we need to send messages with 10-15 seconds delay during last 1km of descend.
please note that base elevation in eastern Washington is quite higher than sea level.
